### ISSUE TITLE
gdfuse empty files and folders after upload

### ISSUE THREAD

**Issue by uchittka** [noahajac/gdfuse-automount#1]
Using opensuse leap 15.4 and google-drive-ocamlfuse.
Files and folders uploading with no problem. But in google drive web there are only files with correct name but all with 0 bytes. The curl.log says:
[0.274337] curl: info:   Trying 142.250.187.180:443...
[0.286861] curl: info: Connected to gd-ocaml-auth.appspot.com (142.250.187.180) port 443 (#0)
[0.287690] curl: info: ALPN, offering h2
[0.287722] curl: info: ALPN, offering http/1.1

df ~/googledrive gives:
Dateisystem            1K-Blöcke  Benutzt Verfügbar Verw% Eingehängt auf
google-drive-ocamlfuse 104857600 50039576  54818024   48% /home/xxxxxxx/googledrive

Thanks for any help

**Comment by noahajac** [comment]
Your issue seems to be with [google-drive-ocamlfuse](https://github.com/astrada/google-drive-ocamlfuse). This repo is simply a wrapper script that automatically mounts Google Drive using it. You can try modifying the mount command or playing with the gdfuse config, but I don't think this is an issue with the script. I will reopen if evidence shows otherwise.

Thank you!
